### ISSUE TITLE
Support Julia 0.5

### ISSUE THREAD

**Issue by mykelk** [sisl/Smile.jl#2]
It looks like there is an issue with supporting Julia 0.5:
![image](https://cloud.githubusercontent.com/assets/6294079/17274574/79ad7394-569c-11e6-86df-c77af2bfbc80.png)

A nice way to test things out on 0.5 before you install it on your own machine is to use JuliaBox.

**Comment by tawheeler** [comment]
Smile will not support Julia 0.5, as documented on the package README
